[tasks]
check = "trunk check --all --fix"
check_green = "mise run fmt && mise run check && cargo check && cargo build && mise run coverage"
coverage = "cargo tarpaulin --config tarpaulin.toml"
coverage-watch = "cargo watch -x 'tarpaulin --config tarpaulin.toml'"
fmt = "trunk fmt --all"
repomix = "bunx repomix --copy"
"sequence-20250806-151839ftft t ft" = "mise run coverage-watch && mise run check_green"

[tools]
rust = "latest"
trunk = "latest"
